url: http://127.0.0.1
baseurl:

# Site settings
title: Fernando "ferox" dos Santos
email: fernando@ferox.tk
description: "Hacker. Open Source Specialist. Fedora Ambassador."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3c6eb4
  secondary: 3663a2
  secondary-dark: 24426c

# Team names, titles and social links
people:

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: linkedin
    url: https://www.linkedin.com/in/ferox
  - title: twitter
    url: https://twitter.com/hacker_ferox
  - title: facebook
    url: https://facebook.com/hacker.ferox
  - title: instagram
    url: https://www.instagram.com/hacker.ferox
  - title: bitbucket
    url: http://bitbucket.org/ferox
  - title: github
    url: http://github.com/ferox

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
